name: Cleanup Cloudflare work

on:
  #push:
  #  branches: [ main ]
  #schedule:
   # - cron: '0 0 * * *'  # 每天 UTC 0点运行
  workflow_dispatch:      # 允许手动触发

jobs:
  cleanup:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Run cleanup script
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: python 1.py 
      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@v2.0.6
        with:
         token: ${{ secrets.GITHUB_TOKEN }}
         repository: ${{ github.repository }}
         retain_days: 1
         keep_minimum_runs: 0
